import type { ThreadsPost } from './threads';

// Mock leads — used when no Threads API token is configured, so the dashboard
// shows realistic content during development. Replace by real Threads API
// once EXPO_PUBLIC_THREADS_ACCESS_TOKEN is set.
export const MOCK_LEADS: ThreadsPost[] = [
  {
    id: 'mock-1',
    username: 'lilkayraps',
    text: 'Looking for a producer for my next EP 🔥 Need that hard trap sound with melodic vibes. Open to new producers. Budget flexible — DM me',
    timestamp: new Date(Date.now() - 12 * 60 * 1000).toISOString(),
    permalink: '',
    match_tag: 'Production Needed',
    threads_url: 'https://www.threads.net/@lilkayraps',
    instagram_url: 'https://www.instagram.com/lilkayraps',
  },
  {
    id: 'mock-2',
    username: 'jordan.mvp',
    text: 'Need beats for my mixtape dropping next month. Hip-hop / drill vibes. Send your beat packs 💯',
    timestamp: new Date(Date.now() - 45 * 60 * 1000).toISOString(),
    permalink: '',
    match_tag: 'Beat Request',
    threads_url: 'https://www.threads.net/@jordan.mvp',
    instagram_url: 'https://www.instagram.com/jordan.mvp',
  },
  {
    id: 'mock-3',
    username: 'sarahsings_',
    text: 'URGENT: need mixing engineer for 3 R&B tracks. Need to be done by Friday. Have $300 budget. Hit me asap please 🙏',
    timestamp: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    permalink: '',
    match_tag: 'Mixing / Mastering Needed',
    threads_url: 'https://www.threads.net/@sarahsings_',
    instagram_url: 'https://www.instagram.com/sarahsings_',
  },
  {
    id: 'mock-4',
    username: 'mike_dthegoat',
    text: 'Where can I buy drill beats? Need that UK drill sound for a song this weekend. Drop your beat store',
    timestamp: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
    permalink: '',
    match_tag: 'Beat Request',
    threads_url: 'https://www.threads.net/@mike_dthegoat',
    instagram_url: 'https://www.instagram.com/mike_dthegoat',
  },
  {
    id: 'mock-5',
    username: 'amaraworldwide',
    text: 'Need someone to master 5 of my songs for streaming. Afrobeats / R&B. Anyone available this week?',
    timestamp: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
    permalink: '',
    match_tag: 'Mixing / Mastering Needed',
    threads_url: 'https://www.threads.net/@amaraworldwide',
    instagram_url: 'https://www.instagram.com/amaraworldwide',
  },
  {
    id: 'mock-6',
    username: 'travii.x',
    text: 'Looking for producer to help me build out a full project. I write/sing, need someone who can produce from my voice memos. Long-term collab',
    timestamp: new Date(Date.now() - 8 * 60 * 60 * 1000).toISOString(),
    permalink: '',
    match_tag: 'Production Needed',
    threads_url: 'https://www.threads.net/@travii.x',
    instagram_url: 'https://www.instagram.com/travii.x',
  },
  {
    id: 'mock-7',
    username: 'kingofqueens.213',
    text: 'Need vocals mixed and tuned. Got 8 songs ready. What yall charge per song? Reply with rates 🎤',
    timestamp: new Date(Date.now() - 11 * 60 * 60 * 1000).toISOString(),
    permalink: '',
    match_tag: 'Mixing / Mastering Needed',
    threads_url: 'https://www.threads.net/@kingofqueens.213',
    instagram_url: 'https://www.instagram.com/kingofqueens.213',
  },
  {
    id: 'mock-8',
    username: 'nayaflowz',
    text: 'I need beats!!! Type beat artists like Don Toliver, Travis Scott. Hit me up with your loops 🌊',
    timestamp: new Date(Date.now() - 18 * 60 * 60 * 1000).toISOString(),
    permalink: '',
    match_tag: 'Beat Request',
    threads_url: 'https://www.threads.net/@nayaflowz',
    instagram_url: 'https://www.instagram.com/nayaflowz',
  },
];
