ALTER TABLE leads ADD COLUMN IF NOT EXISTS verdict TEXT;
ALTER TABLE leads ADD COLUMN IF NOT EXISTS why TEXT;
ALTER TABLE leads ADD COLUMN IF NOT EXISTS dm TEXT;
CREATE INDEX IF NOT EXISTS leads_verdict_idx ON leads (verdict);
